version: '3.3'

services:
  web:
    image: forum
    ports:
      - "80:80"
    environment:
      - DB_SERVER=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=forum_db
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum_db

networks:
  default:
    driver: bridge
